name: Generate requirements.txt

on:
  push:
    branches:
      - 'konflux/mintmaker/**/*poetry-deps'

jobs:
  generate-requirements-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Python tools
        run: |
          # https://github.com/hermetoproject/pybuild-deps/issues/295
          pip install --upgrade "pip<25.1" && pip install --upgrade poetry~=2.1.3 poetry-plugin-export pybuild-deps pip-tools

      - name: Export requirements.txt
        run: |
          poetry export -f requirements.txt --output requirements.txt
          poetry export --only dev -f requirements.txt --output requirements-dev.txt
          pybuild-deps compile --generate-hashes requirements.txt -o requirements-build.txt

          # Prepare requirements-build.in from pyproject.toml
          sed -n '/^\[build-system\]/,/^\[/p' pyproject.toml | \
            grep 'requires[[:space:]]*=' | \
            sed 's/.*requires[[:space:]]*=[[:space:]]*\[\(.*\)\]/\1/' | \
            sed 's/"//g; s/,[[:space:]]*/\n/g' | \
            sed 's/^[[:space:]]*//; s/[[:space:]]*$$//; /^$$/d' > requirements-build.in

          pip-compile --allow-unsafe --generate-hashes -o requirements-extra.txt requirements-build.in

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: re-generate requirements.txt files"
            git push
          fi
